### ISSUE TITLE
Dexie compatibility db.version in dexie.org must be integer

### ISSUE THREAD

**Issue by job3dot5** [marmotz/LSDManager#7]
https://github.com/marmotz/LSDManager/blob/5ac186d1c3edb5006e8798dfe96b5e77d1b1ca86/src/LSDManager.js#L931

The for loop convert integer to string.

@tofix ? this.$database.version(parseInt(version)).stores(

**Comment by marmotz** [comment]
Fixed in b0b8a55ed471fb116a80fda7691e41b671384331
